// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/app:gen_app_buildconfig"

#ifndef APP_APPBUILDCONFIG_H_
#define APP_APPBUILDCONFIG_H_

#define CHIP_CONFIG_IM_ENABLE_SCHEMA_CHECK 0

#endif  // APP_APPBUILDCONFIG_H_
